### ISSUE TITLE
Permissions : Exception Java lors du lancement du serveur

### ISSUE THREAD

**Issue by eloam** [eloam/brogond-minecraft-server#5]
Scénario de reproduction :
- Démarrer le serveur
- L'erreur suivante s'affiche dans les logs :
`[19:34:08 INFO]: [LordPermission] Enabling LordPermission v1.0
[19:34:08 ERROR]: Cannot load configuration from stream
org.bukkit.configuration.InvalidConfigurationException: Top level is not a Map.
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:58) ~[spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) ~[spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:239) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:174) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:142) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at me.Gomze.LordPermissions.Main.LordPermissions.onEnable(LordPermissions.java:17) [LordPermissionsEN.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]`

**Comment by eloam** [comment]
Le plugin LordPermissions à été remplacé par PermissionsEx. Bug corrigé.
